/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recordings
         * @description List all recordings with optional filters.
         */
        get: operations["list_recordings_api_v1_recordings_get"];
        put?: never;
        /**
         * Create Recording
         * @description Start a new recording session.
         */
        post: operations["create_recording_api_v1_recordings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Recordings
         * @description Scan recordings directory and import unregistered audio files.
         */
        post: operations["sync_recordings_api_v1_recordings_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/consistency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Consistency
         * @description Check DB ↔ filesystem consistency for orphan records/files.
         */
        get: operations["check_consistency_api_v1_recordings_consistency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/consistency/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consistency Cleanup
         * @description Clean up orphan records or files discovered by consistency check.
         *
         *     Supported actions:
         *     - ``delete_records``: Remove DB records with no audio file on disk.
         *     - ``delete_files``: Remove audio files with no matching DB record.
         *     - ``import_files``: Import orphan files into the DB via filesystem sync.
         *
         *     Args:
         *         body: Action type and the record IDs or file paths to process.
         */
        post: operations["consistency_cleanup_api_v1_recordings_consistency_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recording
         * @description Get details for a single recording.
         */
        get: operations["get_recording_api_v1_recordings__recording_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Recording
         * @description Delete a recording and clean up associated files and vectors.
         */
        delete: operations["delete_recording_api_v1_recordings__recording_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recording Audio
         * @description Serve the WAV audio file for a recording.
         */
        get: operations["get_recording_audio_api_v1_recordings__recording_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Recording
         * @description Process an imported recording: transcribe, summarize, and embed.
         *
         *     Runs the full offline pipeline for recordings imported via filesystem sync
         *     (as opposed to live WebSocket recording). Steps:
         *     1. Validate the recording exists and has an audio file.
         *     2. Transcribe the entire audio file via faster-whisper.
         *     3. Group segments by minute and create per-minute transcripts.
         *     4. Summarize each minute and embed into ChromaDB.
         *     5. Finalize the recording status to "completed".
         *
         *     Args:
         *         recording_id: ID of the imported recording to process.
         *
         *     Raises:
         *         VoiceVaultError: If the recording is active, already processed, or missing audio.
         */
        post: operations["process_recording_api_v1_recordings__recording_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Stop Recording
         * @description Stop an active recording and trigger post-processing.
         */
        patch: operations["stop_recording_api_v1_recordings__recording_id__stop_patch"];
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/classifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Classifications
         * @description Get classification results for a recording.
         */
        get: operations["get_classifications_api_v1_recordings__recording_id__classifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Recording
         * @description Export recording as Obsidian-compatible Markdown.
         *
         *     Generates a Markdown file with YAML frontmatter, template-driven sections,
         *     and optional ``[[wikilinks]]`` to related recordings discovered via RAG.
         *
         *     Args:
         *         recording_id: ID of the recording to export.
         *         body: Optional export configuration (format, vault path, etc.).
         */
        post: operations["export_recording_api_v1_recordings__recording_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Summaries
         * @description List 1-minute summaries for a recording.
         */
        get: operations["list_summaries_api_v1_recordings__recording_id__summaries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/hour-summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Hour Summaries
         * @description List hour-level summaries for a recording.
         *
         *     Returns cached hour summaries if available. Otherwise generates
         *     them on-demand from existing minute summaries using hierarchical
         *     compression.
         */
        get: operations["list_hour_summaries_api_v1_recordings__recording_id__hour_summaries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Range
         * @description Cross-boundary range extraction and re-summarization.
         *
         *     Allows users to select any time range (e.g., minute 40–80) spanning
         *     hour boundaries. Fetches 1-min summaries in that range and produces
         *     a single unified summary via the LLM.
         *
         *     Args:
         *         recording_id: ID of the recording.
         *         body: Start and end minute for the range to extract.
         */
        post: operations["extract_range_api_v1_recordings__recording_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reindex Summaries
         * @description Rebuild the ChromaDB vector index from all existing summaries.
         *
         *     Iterates over every recording and re-embeds all their minute summaries.
         *     Useful after changing the embedding model or recovering from data loss.
         */
        post: operations["reindex_summaries_api_v1_rag_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rag Query
         * @description Search past recordings with a natural-language query.
         *
         *     Pipeline: embed query -> ChromaDB similarity search -> metadata filter
         *     -> LLM generates a grounded answer with source citations.
         *     The query and results are also persisted for analytics.
         */
        post: operations["rag_query_api_v1_rag_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/similar/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rag Similar
         * @description Find recordings similar to the given recording via vector similarity.
         */
        get: operations["rag_similar_api_v1_rag_similar__recording_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description List all templates, optionally filtering to active only.
         */
        get: operations["list_templates_api_v1_templates_get"];
        put?: never;
        /**
         * Create Template
         * @description Create a new classification template.
         */
        post: operations["create_template_api_v1_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Template
         * @description Soft-delete a template by setting is_active=False.
         */
        delete: operations["delete_template_api_v1_templates__template_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Template
         * @description Update an existing template.
         */
        patch: operations["update_template_api_v1_templates__template_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClassificationResponse
         * @description A classification result for a recording segment.
         */
        ClassificationResponse: {
            /** Id */
            id: number;
            /** Recording Id */
            recording_id: number;
            /** Template Name */
            template_name: string;
            /** Start Minute */
            start_minute: number;
            /** End Minute */
            end_minute: number;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Result */
            result?: {
                [key: string]: unknown;
            };
            /** Export Path */
            export_path?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CleanupRequest
         * @description Request body for consistency cleanup actions.
         */
        CleanupRequest: {
            /** Action */
            action: string;
            /** Record Ids */
            record_ids?: number[];
            /** File Paths */
            file_paths?: string[];
        };
        /**
         * CleanupResponse
         * @description Response from consistency cleanup.
         */
        CleanupResponse: {
            /**
             * Processed
             * @default 0
             */
            processed: number;
            /** Errors */
            errors?: string[];
        };
        /**
         * ConsistencyResponse
         * @description Response from DB ↔ filesystem consistency check.
         */
        ConsistencyResponse: {
            /**
             * Total Db Records
             * @default 0
             */
            total_db_records: number;
            /**
             * Total Fs Files
             * @default 0
             */
            total_fs_files: number;
            /** Orphan Records */
            orphan_records?: components["schemas"]["OrphanRecord"][];
            /** Orphan Files */
            orphan_files?: components["schemas"]["OrphanFile"][];
            /**
             * Healthy Count
             * @default 0
             */
            healthy_count: number;
        };
        /**
         * DeleteRecordingResponse
         * @description Response from recording deletion with file cleanup.
         */
        DeleteRecordingResponse: {
            /** Recording Id */
            recording_id: number;
            /**
             * Db Deleted
             * @default true
             */
            db_deleted: boolean;
            /**
             * Audio Deleted
             * @default false
             */
            audio_deleted: boolean;
            /**
             * Exports Deleted
             * @default 0
             */
            exports_deleted: number;
            /**
             * Vectors Deleted
             * @default 0
             */
            vectors_deleted: number;
        };
        /**
         * ExtractRangeRequest
         * @description POST /recordings/{id}/extract request body.
         *
         *     Allows users to select any arbitrary minute range for re-summarization.
         *     The range can span hour boundaries transparently.
         */
        ExtractRangeRequest: {
            /** Start Minute */
            start_minute: number;
            /** End Minute */
            end_minute: number;
        };
        /**
         * ExtractRangeResponse
         * @description Response from cross-boundary range extraction.
         */
        ExtractRangeResponse: {
            /** Recording Id */
            recording_id: number;
            /** Start Minute */
            start_minute: number;
            /** End Minute */
            end_minute: number;
            /** Summary Text */
            summary_text: string;
            /** Keywords */
            keywords?: string[];
            /** Included Minutes */
            included_minutes?: number[];
            /**
             * Source Count
             * @default 0
             */
            source_count: number;
            /**
             * Model Used
             * @default
             */
            model_used: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description GET /health response.
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * HourSummaryResponse
         * @description A single hour-level summary.
         */
        HourSummaryResponse: {
            /** Id */
            id: number;
            /** Recording Id */
            recording_id: number;
            /** Hour Index */
            hour_index: number;
            /** Summary Text */
            summary_text: string;
            /** Keywords */
            keywords?: string[];
            /** Topic Segments */
            topic_segments?: {
                [key: string]: unknown;
            }[];
            /**
             * Token Count
             * @default 0
             */
            token_count: number;
            /**
             * Model Used
             * @default
             */
            model_used: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ObsidianExportRequest
         * @description POST /recordings/{id}/export request body.
         */
        ObsidianExportRequest: {
            /**
             * Format
             * @default obsidian
             */
            format: string;
            /**
             * Include Transcript
             * @default false
             */
            include_transcript: boolean;
            /** Vault Path */
            vault_path?: string | null;
        };
        /**
         * ObsidianExportResponse
         * @description Response from an Obsidian Markdown export.
         */
        ObsidianExportResponse: {
            /** File Path */
            file_path: string;
            /** Markdown Content */
            markdown_content: string;
            /** Frontmatter */
            frontmatter?: {
                [key: string]: unknown;
            };
        };
        /**
         * OrphanFile
         * @description An audio file on disk with no matching DB record.
         */
        OrphanFile: {
            /** File Path */
            file_path: string;
            /** File Name */
            file_name: string;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /** Modified At */
            modified_at?: string | null;
        };
        /**
         * OrphanRecord
         * @description A DB recording whose audio file is missing from disk.
         */
        OrphanRecord: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /** Status */
            status: string;
            /** Audio Path */
            audio_path?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /**
         * ProcessRecordingResponse
         * @description Response from processing an imported recording.
         */
        ProcessRecordingResponse: {
            /** Recording Id */
            recording_id: number;
            /**
             * Status
             * @default completed
             */
            status: string;
            /**
             * Total Minutes
             * @default 0
             */
            total_minutes: number;
            /**
             * Transcripts Created
             * @default 0
             */
            transcripts_created: number;
            /**
             * Summaries Created
             * @default 0
             */
            summaries_created: number;
            /**
             * Embeddings Created
             * @default 0
             */
            embeddings_created: number;
        };
        /**
         * RAGQueryRequest
         * @description POST /rag/query request body.
         *
         *     Supports natural-language queries with optional metadata filters
         *     for date range, category, and keyword narrowing.
         */
        RAGQueryRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
            /**
             * Min Similarity
             * @default 0.3
             */
            min_similarity: number;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /** Category */
            category?: string | null;
            /** Keywords */
            keywords?: string[] | null;
        };
        /**
         * RAGQueryResponse
         * @description Response from a RAG search query.
         */
        RAGQueryResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources?: components["schemas"]["RAGSource"][];
            /**
             * Model Used
             * @default
             */
            model_used: string;
            /**
             * Query Time Ms
             * @default 0
             */
            query_time_ms: number;
        };
        /**
         * RAGSource
         * @description A single source reference within a RAG answer.
         */
        RAGSource: {
            /** Recording Id */
            recording_id: number;
            /** Minute Index */
            minute_index: number;
            /** Summary Text */
            summary_text: string;
            /** Similarity */
            similarity: number;
            /** Date */
            date: string;
            /**
             * Category
             * @default
             */
            category: string;
        };
        /**
         * RecordingCreate
         * @description POST /recordings request body (optional fields).
         */
        RecordingCreate: {
            /** Title */
            title?: string | null;
            /** Context */
            context?: string | null;
        };
        /**
         * RecordingResponse
         * @description Standard recording representation returned by the API.
         */
        RecordingResponse: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /** Context */
            context?: string | null;
            status: components["schemas"]["RecordingStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Total Minutes
             * @default 0
             */
            total_minutes: number;
            /** Audio Path */
            audio_path?: string | null;
        };
        /**
         * RecordingStatus
         * @description Possible states for a recording session.
         *
         *     Lifecycle: active -> processing -> completed | failed
         *     Imported recordings start directly as "imported".
         * @enum {string}
         */
        RecordingStatus: "active" | "processing" | "completed" | "failed" | "imported";
        /**
         * ReindexDetailResponse
         * @description Detailed response from a reindex operation.
         */
        ReindexDetailResponse: {
            /**
             * Status
             * @default completed
             */
            status: string;
            result?: components["schemas"]["ReindexResponse"];
        };
        /**
         * ReindexResponse
         * @description Response from a reindex operation.
         */
        ReindexResponse: {
            /**
             * Reindexed
             * @default 0
             */
            reindexed: number;
            /**
             * Errors
             * @default 0
             */
            errors: number;
            /**
             * Total In Store
             * @default 0
             */
            total_in_store: number;
        };
        /**
         * SummaryResponse
         * @description A single 1-minute summary.
         */
        SummaryResponse: {
            /** Id */
            id: number;
            /** Recording Id */
            recording_id: number;
            /** Minute Index */
            minute_index: number;
            /** Summary Text */
            summary_text: string;
            /** Keywords */
            keywords?: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Corrections */
            corrections?: components["schemas"]["TranscriptionCorrection"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SyncResponse
         * @description Response from filesystem → DB sync operation.
         */
        SyncResponse: {
            /**
             * Scanned
             * @default 0
             */
            scanned: number;
            /**
             * New Imports
             * @default 0
             */
            new_imports: number;
            /**
             * Already Exists
             * @default 0
             */
            already_exists: number;
            /** Errors */
            errors?: string[];
        };
        /**
         * TemplateCreate
         * @description POST /templates request body.
         */
        TemplateCreate: {
            /** Name */
            name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Triggers */
            triggers?: string[];
            /**
             * Output Format
             * @default markdown
             */
            output_format: string;
            /** Fields */
            fields?: {
                [key: string]: unknown;
            }[];
            /**
             * Icon
             * @default
             */
            icon: string;
            /**
             * Priority
             * @default 0
             */
            priority: number;
        };
        /**
         * TemplateResponse
         * @description Standard template representation returned by the API.
         */
        TemplateResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Triggers */
            triggers?: string[];
            /**
             * Output Format
             * @default markdown
             */
            output_format: string;
            /** Fields */
            fields?: {
                [key: string]: unknown;
            }[];
            /**
             * Icon
             * @default
             */
            icon: string;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TranscriptionCorrection
         * @description A single STT error correction made by the LLM summarizer.
         */
        TranscriptionCorrection: {
            /** Original */
            original: string;
            /** Corrected */
            corrected: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_recordings_api_v1_recordings_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recording_api_v1_recordings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RecordingCreate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_recordings_api_v1_recordings_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
    check_consistency_api_v1_recordings_consistency_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsistencyResponse"];
                };
            };
        };
    };
    consistency_cleanup_api_v1_recordings_consistency_cleanup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_api_v1_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recording_api_v1_recordings__recording_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteRecordingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_audio_api_v1_recordings__recording_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_recording_api_v1_recordings__recording_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessRecordingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_recording_api_v1_recordings__recording_id__stop_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_classifications_api_v1_recordings__recording_id__classifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassificationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_recording_api_v1_recordings__recording_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ObsidianExportRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObsidianExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_summaries_api_v1_recordings__recording_id__summaries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hour_summaries_api_v1_recordings__recording_id__hour_summaries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HourSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_range_api_v1_recordings__recording_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractRangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_summaries_api_v1_rag_reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexDetailResponse"];
                };
            };
        };
    };
    rag_query_api_v1_rag_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RAGQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RAGQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rag_similar_api_v1_rag_similar__recording_id__get: {
        parameters: {
            query?: {
                top_k?: number;
            };
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RAGSource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_templates_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_v1_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_v1_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_v1_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
